# Generated by Django 6.0.2 on 2026-02-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('procurement_manager', 'Procurement Manager'), ('staff', 'Staff')], default='procurement_manager', max_length=20),
        ),
    ]
