# Generated by Django 6.0.2 on 2026-03-18 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='contracts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.TextField(blank=True)),
                ('penalty_clauses', models.TextField(blank=True)),
                ('delivery_schedule', models.TextField(blank=True)),
                ('contract_duration', models.TextField(blank=True)),
                ('compliance_obligations', models.TextField(blank=True)),
                ('full_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='contracts.contract')),
            ],
        ),
    ]
