# Generated by Django 6.0.2 on 2026-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PURCHASED', 'Purchased'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
    ]
